### ISSUE TITLE
Using reference for raw pointer

### ISSUE THREAD

**Issue by tathanhdinh** [tandasat/UefiVarMonitor#2]
Hello,

IMHO, we can change the raw pointer in the signature of the function

https://github.com/tandasat/UefiVarMonitor/blob/4cddc72d01c1d626d06095f97380c1b1a9a6ca58/uefi-var-monitor/src/main.rs#L148-L150

using an ABI compatible:

```rust
#[no_mangle]
unsafe fn efi_main(_image_handle: efi::Handle, system_table: Option<&'_ mut efi::SystemTable>) -> efi::Status {
    assert!(system_table.is_some());
    log!("Driver being loaded");

    let system_table = system_table.unwrap();
```

then in the function, we don't need to dereference `system_table` any more, just use the reference `system_table` instead of `*system_table`.

**Comment by tandasat** [comment]
I wanted to stick with a pointer for the system table mainly because to keep direct translation from C for this pre-defined interface (ie, EFI entry point). But I 100% agree that using references makes code significantly better. I rewrote code to use them where makes sense. 

Thanks for suggestion again. I am learning a lot :)
